[#ftl output_format="HTML"]
        <!DOCTYPE html>
          <html lang="en">
          <head>
          
          
          
          <style>* { box-sizing: border-box; } body {margin: 0;}*{box-sizing:border-box;}body{margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;}</style>
          
          </head>
          <body>[#macro main]
  <meta charset="UTF-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>web/commons.ftlh
  </title><form method="post" enctype="application/x-www-form-urlencoded"><div class="row"><div class="d-flex align-items-center flex-column link-secondary lh-1">
		Stuck or changed your mind? &lt;#-- I would like to t --&gt;
		<button type="submit" id="skipped" name="skipped" value="" class="btn btn-link p-0 ps-1">
		  Use a different enrollment method
		</button></div></div></form>
  [/#macro]

</body>
          </html>